{{- if .Values.redis.enabled -}}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  kubernetesConfig:
    image: {{ .Values.redis.redisStandalone.image }}:{{ .Values.redis.redisStandalone.tag }}
    imagePullPolicy: {{ .Values.redis.redisStandalone.imagePullPolicy }}
    resources:
      {{- toYaml .Values.redis.redisStandalone.resources | nindent 6 }}
    securityContext:
      fsGroup: 1000
      runAsUser: 1000
    redisSecret:
      name: {{ .Values.redis.secretName | default "onyx-redis" }}
      key: redis_password
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
{{- end }}